name: client
on:
  push:
    branches:
      - '*'
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - run: cd client && npm install
      - run: cd client && npm run lint
      - run: cd client && npm run build
