name: publish
on:
  create:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ts-node-template"
          heroku_email: "${{secrets.HEROKU_EMAIL}}"
          appdir: "."
