name: server
on:
  push:
    branches:
      - '*'
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - run: cd server && npm install
      - run: cd server && npm run lint
      - run: cd server && npm run build
